
services:
  vogueshopping_website:
    build: .
    container_name: vogueshopping
    image: vogueshopping:latest
    networks:
      - vogueshopping_network
    restart: always

networks:
  vogueshopping_network:
    external: true
